apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: practice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
  image:  nginx

